### ISSUE TITLE
hb_correction overrides manual rbc:m ratio

### ISSUE THREAD

**Issue by YonniFriedlander** [TeamXenonDuke/xenon-gas-exchange-consortium#82]
I've entered an RBC:M ratio in the config file using
```
self.rbc_m_ratio = 0.401
``` 

When I enter a Hb value in the config file using the following code, the RBC:M ratio printed on the report is _not_ the value I enter manually

````
# set what kind of hemoglobin correction to use
self.hb_correction_key = constants.HbCorrectionKey.RBC_AND_MEMBRANE.value
# define subject hemoglobin in g/dL
self.hb = 12.5
```

However, when I comment out the Hb correction from the config file, the RBC:M is correctly reported as 0.401.

Other than how to fix the issue, I'm wondering if this is a reporting problem or is the wrong RBC:M propagated through the calculations?

Thanks as always,
Yonni

**Comment by davidmummy** [comment]
Hi Yonni -- I think this is actually the expected behavior, assuming it's not going completely off the rails with your RBC:M value. The Hb correction affects both the RBC and the M values, and the Hb-corrected version is what's used in the report. 

A Hb value of 12.5 is a bit lower than normal, so we'd expect the correction to bring the RBC signal UP and the membrane DOWN. The RBC:M thus gets a double whammy and gets driven upward to some degree. It shouldn't huge for an Hb of 12.5 but definitely noticeable. 

Is that what you're seeing?

Note the original RBC:M is still used for the Dixon decomposition. The Hb-corrected version just gets output in the report.

**Comment by davidmummy** [comment]
No problem! Yeah I have to think it through every time to remember which way the corrections go...

Closing this bug.
